### PR TITLE
Added A* Pathfinding Algorithm with GUI

### PR DESCRIPTION
**Pull request by proghead00**

### CODE REVIEW

**Review by abhpd — CHANGES_REQUESTED** [review]
@proghead00 Thanks for a very nice PR, Just put the file under the "Projects" folder. Your project path should be like `Python/Projects/A-Star-GUI/<your-files>`

**Comment by proghead00** [comment]
@abhpd What do you want me to do, create a folder named **Projects** and inside that I must put my script?

**Comment by abhpd** [comment]
@proghead00 Yes, create a **Projects** folder under **Pyhton** folder and there you can put your **A-Star-GUI** project folder.

**Comment by abhpd** [comment]
Changes committed with #11

**Pull request closed without merging**
