### PR TITLE
Add JS Project-Timer

### PR DESCRIPTION
**Pull request by neeagwl**
added a JS project with well defined README file.

### CODE REVIEW

**Review by internall — CHANGES_REQUESTED** [review]
Why are there a copies of the same files?

**Comment by neeagwl** [comment]
Changes Updated. Copies of same files removed.

**Comment by neeagwl** [comment]
> Why are there multiple copies of the same files?

Removed copies of same file.

**Review by internall — APPROVED** [review]
**LGTM!**

**Comment by internall** [comment]
@neeagwl You should add more comments to algorithms you uploaded on "Graph Theory Algorithms".

**Pull request merged**
