### PR TITLE
Create Write Priority Queue Using Heap.java

### PR DESCRIPTION
**Pull request by jyotidhatarwal**
Write Priority Queue Using Heap in java

Sample Input:
add 10
add 20
add 30
add 40
peek
add 50
peek
remove
peek
remove
peek
remove
peek
remove
peek
quit

Sample output:
10
10
10
20
20
30
30
40
40
50

### CODE REVIEW

**Review by internall — CHANGES_REQUESTED** [review]
https://github.com/abhpd/hacktoberfest2020/issues/2

**Comment by jyotidhatarwal** [comment]
> #2

Hey what changes do you need because this code works fine on my system

**Comment by internall** [comment]
> > #2
> 
> Hey what changes do you need because this code works fine on my system

Hello sir, you have to change directory, as written here #2

**Comment by internall** [comment]
Closing PR for #243.

**Pull request closed without merging**
