### PR TITLE
Added Bubble Sort in language c++

### PR DESCRIPTION
**Pull request by nikhilgupta2001**
Added Bubble Sort in language c++

### CODE REVIEW

**Comment by abhpd** [comment]
@nikhilgupta2001 Put these files under `C++/Algorithms/Sorting/`

**Review by abhpd — CHANGES_REQUESTED** [review]
The code is A-OK just we need them at their correct location.

**Comment by nikhilgupta2001** [comment]
please also label it as hacktoberfest to make it counted

**Review by abhpd — APPROVED** [review]
@nikhilgupta2001 Good job! Thanks for contributing. ❤️

**Pull request merged**
