### PR TITLE
Create Merge K Sorted Lists.java

### PR DESCRIPTION
**Pull request by jyotidhatarwal**
Merge K Sorted Lists in java
Constraints:
Space complextiy = O(k)
Time complexity = nlogk
where k is the number of lists and n is number of elements across all lists.

Sample input:
4
5
10 20 30 40 50
7
5 7 9 11 19 55 57
3
1 2 3
2
32 39
Sample output:
1 2 3 5 7 9 10 11 19 20 30 32 39 40 50 55 57

### CODE REVIEW

**Review by internall — CHANGES_REQUESTED** [review]
https://github.com/abhpd/hacktoberfest2020/issues/2

**Comment by jyotidhatarwal** [comment]
> #2

hey what changes do you need because this code works fine on my system.

**Comment by internall** [comment]
> > #2
> 
> hey what changes do you need because this code works fine on my system.

Hello sir, you have to change directory, as written here https://github.com/abhpd/hacktoberfest2020/issues/2

**Comment by internall** [comment]
Closing PR for #245.

**Pull request closed without merging**
