### PR TITLE
Added a program that calculates the current date/time with Java

### PR DESCRIPTION
**Pull request by Fonta22**

### CODE REVIEW

**Comment by abhpd** [comment]
@Fonta22 Put this file under `Java/Projects/`

**Comment by Fonta22** [comment]
Ok, now I do it 👍

**Comment by abhpd** [comment]
@Fonta22 You're supposed to create a folder if you don't find any. For example, this will go under `Java/Projects/`.

**Comment by Fonta22** [comment]
Ok, I'll make a new PR but into the created 'Projects' folder. @abhpd

**Pull request closed without merging**
